import { writeFileSync, mkdirSync } from 'fs';
import { join } from 'path';
import type { AuthMethod, Backend, ModuleResult } from '../types/index.js';

export async function setupAuth(
  methods: AuthMethod[],
  backend: Backend,
  projectPath: string
): Promise<ModuleResult> {
  const filesCreated: string[] = [];
  const authDir = join(projectPath, 'src', 'lib', 'auth');
  mkdirSync(authDir, { recursive: true });

  if (backend === 'supabase') {
    const content = `// Supabase Auth Configuration
// Generated by AppForge

import { createClient } from '@supabase/supabase-js';

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL || process.env.EXPO_PUBLIC_SUPABASE_URL || '';
const supabaseAnonKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY || process.env.EXPO_PUBLIC_SUPABASE_ANON_KEY || '';

export const supabase = createClient(supabaseUrl, supabaseAnonKey);

${methods.includes('email') ? `
export async function signInWithEmail(email: string, password: string) {
  return supabase.auth.signInWithPassword({ email, password });
}

export async function signUpWithEmail(email: string, password: string) {
  return supabase.auth.signUp({ email, password });
}
` : ''}
${methods.includes('social') ? `
export async function signInWithGoogle() {
  return supabase.auth.signInWithOAuth({ provider: 'google' });
}

export async function signInWithGitHub() {
  return supabase.auth.signInWithOAuth({ provider: 'github' });
}

export async function signInWithApple() {
  return supabase.auth.signInWithOAuth({ provider: 'apple' });
}
` : ''}
${methods.includes('magic-link') ? `
export async function signInWithMagicLink(email: string) {
  return supabase.auth.signInWithOtp({ email });
}
` : ''}
export async function signOut() {
  return supabase.auth.signOut();
}

export async function getSession() {
  return supabase.auth.getSession();
}

export function onAuthStateChange(callback: (event: string, session: unknown) => void) {
  return supabase.auth.onAuthStateChange(callback);
}
`;
    writeFileSync(join(authDir, 'index.ts'), content, 'utf-8');
    filesCreated.push('src/lib/auth/index.ts');
  } else if (backend === 'firebase') {
    const content = `// Firebase Auth Configuration
// Generated by AppForge

import { getAuth, signInWithPopup, GoogleAuthProvider, GithubAuthProvider, OAuthProvider } from 'firebase/auth';
import { app } from '../firebase';

export const auth = getAuth(app);

${methods.includes('email') ? `
import { signInWithEmailAndPassword, createUserWithEmailAndPassword } from 'firebase/auth';

export async function signInWithEmail(email: string, password: string) {
  return signInWithEmailAndPassword(auth, email, password);
}

export async function signUpWithEmail(email: string, password: string) {
  return createUserWithEmailAndPassword(auth, email, password);
}
` : ''}
${methods.includes('social') ? `
const googleProvider = new GoogleAuthProvider();
const githubProvider = new GithubAuthProvider();
const appleProvider = new OAuthProvider('apple.com');

export async function signInWithGoogle() {
  return signInWithPopup(auth, googleProvider);
}

export async function signInWithGitHub() {
  return signInWithPopup(auth, githubProvider);
}

export async function signInWithApple() {
  return signInWithPopup(auth, appleProvider);
}
` : ''}
${methods.includes('magic-link') ? `
import { sendSignInLinkToEmail } from 'firebase/auth';

export async function signInWithMagicLink(email: string) {
  const actionCodeSettings = {
    url: window.location.origin,
    handleCodeInApp: true,
  };
  return sendSignInLinkToEmail(auth, email, actionCodeSettings);
}
` : ''}
export async function signOut() {
  return auth.signOut();
}

export function onAuthStateChange(callback: (user: unknown) => void) {
  return auth.onAuthStateChanged(callback);
}
`;
    writeFileSync(join(authDir, 'index.ts'), content, 'utf-8');
    filesCreated.push('src/lib/auth/index.ts');
  } else {
    const content = `// Auth Configuration
// Generated by AppForge
// Connect your preferred auth provider here

export interface AuthUser {
  id: string;
  email: string;
  displayName?: string;
}

export async function signIn(email: string, password: string): Promise<AuthUser | null> {
  // TODO: Implement sign in
  throw new Error('Not implemented');
}

export async function signUp(email: string, password: string): Promise<AuthUser | null> {
  // TODO: Implement sign up
  throw new Error('Not implemented');
}

export async function signOut(): Promise<void> {
  // TODO: Implement sign out
  throw new Error('Not implemented');
}
`;
    writeFileSync(join(authDir, 'index.ts'), content, 'utf-8');
    filesCreated.push('src/lib/auth/index.ts');
  }

  return {
    success: true,
    message: `Auth configured with methods: ${methods.join(', ')}`,
    filesCreated,
    packagesInstalled: [],
  };
}
