import { writeFileSync, mkdirSync } from 'fs';
import { join } from 'path';
import type { Backend, ModuleResult } from '../types/index.js';

export async function setupBackend(
  backend: Backend,
  projectPath: string
): Promise<ModuleResult> {
  const filesCreated: string[] = [];
  const libDir = join(projectPath, 'src', 'lib');
  mkdirSync(libDir, { recursive: true });

  switch (backend) {
    case 'supabase': {
      const content = `// Supabase Client Configuration
// Generated by AppForge

import { createClient } from '@supabase/supabase-js';

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL || process.env.EXPO_PUBLIC_SUPABASE_URL || '';
const supabaseAnonKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY || process.env.EXPO_PUBLIC_SUPABASE_ANON_KEY || '';

export const supabase = createClient(supabaseUrl, supabaseAnonKey);

export default supabase;
`;
      writeFileSync(join(libDir, 'supabase.ts'), content, 'utf-8');
      filesCreated.push('src/lib/supabase.ts');

      const envContent = `NEXT_PUBLIC_SUPABASE_URL=your-supabase-url
NEXT_PUBLIC_SUPABASE_ANON_KEY=your-supabase-anon-key
`;
      writeFileSync(join(projectPath, '.env.example'), envContent, 'utf-8');
      filesCreated.push('.env.example');
      break;
    }

    case 'firebase': {
      const content = `// Firebase Configuration
// Generated by AppForge

import { initializeApp } from 'firebase/app';
import { getFirestore } from 'firebase/firestore';
import { getStorage } from 'firebase/storage';

const firebaseConfig = {
  apiKey: process.env.NEXT_PUBLIC_FIREBASE_API_KEY || '',
  authDomain: process.env.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN || '',
  projectId: process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID || '',
  storageBucket: process.env.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET || '',
  messagingSenderId: process.env.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID || '',
  appId: process.env.NEXT_PUBLIC_FIREBASE_APP_ID || '',
};

export const app = initializeApp(firebaseConfig);
export const db = getFirestore(app);
export const storage = getStorage(app);
`;
      writeFileSync(join(libDir, 'firebase.ts'), content, 'utf-8');
      filesCreated.push('src/lib/firebase.ts');

      const envContent = `NEXT_PUBLIC_FIREBASE_API_KEY=your-api-key
NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=your-auth-domain
NEXT_PUBLIC_FIREBASE_PROJECT_ID=your-project-id
NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=your-storage-bucket
NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=your-messaging-sender-id
NEXT_PUBLIC_FIREBASE_APP_ID=your-app-id
`;
      writeFileSync(join(projectPath, '.env.example'), envContent, 'utf-8');
      filesCreated.push('.env.example');
      break;
    }

    case 'pocketbase': {
      const content = `// PocketBase Client Configuration
// Generated by AppForge

import PocketBase from 'pocketbase';

const pbUrl = process.env.NEXT_PUBLIC_POCKETBASE_URL || process.env.EXPO_PUBLIC_POCKETBASE_URL || 'http://127.0.0.1:8090';

export const pb = new PocketBase(pbUrl);

export default pb;
`;
      writeFileSync(join(libDir, 'pocketbase.ts'), content, 'utf-8');
      filesCreated.push('src/lib/pocketbase.ts');
      break;
    }

    case 'appwrite': {
      const content = `// Appwrite Client Configuration
// Generated by AppForge

import { Client, Account, Databases, Storage } from 'appwrite';

const client = new Client();
client
  .setEndpoint(process.env.NEXT_PUBLIC_APPWRITE_ENDPOINT || 'https://cloud.appwrite.io/v1')
  .setProject(process.env.NEXT_PUBLIC_APPWRITE_PROJECT_ID || '');

export const account = new Account(client);
export const databases = new Databases(client);
export const storage = new Storage(client);

export default client;
`;
      writeFileSync(join(libDir, 'appwrite.ts'), content, 'utf-8');
      filesCreated.push('src/lib/appwrite.ts');
      break;
    }
  }

  return {
    success: true,
    message: `${backend} backend configured`,
    filesCreated,
    packagesInstalled: [],
  };
}
