import { writeFileSync, mkdirSync } from 'fs';
import { join } from 'path';
import type { StylingOption, Framework, ModuleResult } from '../types/index.js';

export async function setupStyling(
  styling: StylingOption,
  framework: Framework,
  projectPath: string
): Promise<ModuleResult> {
  const filesCreated: string[] = [];

  switch (styling) {
    case 'tailwind': {
      const configContent = `/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx,vue,svelte,astro}',
  ],
  theme: {
    extend: {},
  },
  plugins: [],
};
`;
      writeFileSync(join(projectPath, 'tailwind.config.js'), configContent, 'utf-8');
      filesCreated.push('tailwind.config.js');

      const cssContent = `@tailwind base;
@tailwind components;
@tailwind utilities;
`;
      const stylesDir = join(projectPath, 'src', 'styles');
      mkdirSync(stylesDir, { recursive: true });
      writeFileSync(join(stylesDir, 'globals.css'), cssContent, 'utf-8');
      filesCreated.push('src/styles/globals.css');

      const postcssContent = `export default {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
};
`;
      writeFileSync(join(projectPath, 'postcss.config.js'), postcssContent, 'utf-8');
      filesCreated.push('postcss.config.js');
      break;
    }

    case 'nativewind': {
      const configContent = `/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./App.{js,jsx,ts,tsx}', './src/**/*.{js,jsx,ts,tsx}'],
  presets: [require('nativewind/preset')],
  theme: {
    extend: {},
  },
  plugins: [],
};
`;
      writeFileSync(join(projectPath, 'tailwind.config.js'), configContent, 'utf-8');
      filesCreated.push('tailwind.config.js');
      break;
    }

    case 'styled-components': {
      const themeDir = join(projectPath, 'src', 'styles');
      mkdirSync(themeDir, { recursive: true });

      const themeContent = `// Theme Configuration
// Generated by AppForge

export const theme = {
  colors: {
    primary: '#667eea',
    secondary: '#764ba2',
    background: '#ffffff',
    surface: '#f5f5f5',
    text: '#333333',
    textSecondary: '#666666',
    error: '#e53e3e',
    success: '#38a169',
  },
  fonts: {
    body: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
    heading: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
    mono: '"SF Mono", "Fira Code", monospace',
  },
  spacing: {
    xs: '0.25rem',
    sm: '0.5rem',
    md: '1rem',
    lg: '1.5rem',
    xl: '2rem',
    xxl: '4rem',
  },
  borderRadius: {
    sm: '4px',
    md: '8px',
    lg: '16px',
    full: '9999px',
  },
} as const;

export type Theme = typeof theme;
`;
      writeFileSync(join(themeDir, 'theme.ts'), themeContent, 'utf-8');
      filesCreated.push('src/styles/theme.ts');
      break;
    }

    case 'css-modules': {
      const stylesDir = join(projectPath, 'src', 'styles');
      mkdirSync(stylesDir, { recursive: true });

      const content = `/* Global Styles */
/* Generated by AppForge */

:root {
  --color-primary: #667eea;
  --color-secondary: #764ba2;
  --color-background: #ffffff;
  --color-surface: #f5f5f5;
  --color-text: #333333;
  --font-body: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
}

* {
  margin: 0;
  padding: 0;
  box-sizing: border-box;
}

body {
  font-family: var(--font-body);
  background: var(--color-background);
  color: var(--color-text);
}
`;
      writeFileSync(join(stylesDir, 'globals.css'), content, 'utf-8');
      filesCreated.push('src/styles/globals.css');
      break;
    }
  }

  return {
    success: true,
    message: `${styling} styling configured`,
    filesCreated,
    packagesInstalled: [],
  };
}
